use crate::types::{Btype, Itype, Jtype, Rtype, Stype, Utype};

#[derive(Debug, PartialEq)]
pub enum Instruction {
    Add(Rtype),
    Addi(Itype),
    And(Rtype),
    Andi(Itype),
    Auipc(Utype),
    Beq(Btype),
    Bne(Btype),
    Blt(Btype),
    Bge(Btype),
    Bltu(Btype),
    Bgeu(Btype),
    Jal(Jtype),
    Jalr(Itype),
    Lui(Utype),
    Lb(Itype),
    Lbu(Itype),
    Lh(Itype),
    Lhu(Itype),
    Lw(Itype),
    Or(Rtype),
    Ori(Itype),
    Sb(Stype),
    Sh(Stype),
    Sll(Rtype),
    Slli(Itype),
    Slt(Rtype),
    Slti(Itype),
    Sltiu(Itype),
    Sltu(Rtype),
    Sra(Rtype),
    Srl(Rtype),
    Srli(Itype),
    Srai(Itype),
    Sw(Stype),
    Sub(Rtype),
    Xor(Rtype),
    Xori(Itype),
}
